name: CI Docker Matrix

on:
  pull_request:

jobs:
  docker-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t xello .
      - run: docker run --rm xello make matrix
