name: CI Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends g++
      - run: make test
